imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    date:
        format: Y-m-d H:i:s
        interval_format: '%%hh%%mm%%ss'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_type%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

old_sound_rabbit_mq:
  connections:
    default:
      host:     'localhost'
      port:     5672
      user:     'guest'
      password: 'guest'
      vhost:    '/'
      lazy:     true
      connection_timeout: 3
      read_write_timeout: 30

      # requires php-amqplib v2.4.1+ and PHP5.4+
      keepalive: true

      # requires php-amqplib v2.4.1+
      heartbeat: 10

      #requires php_sockets.dll
#      use_socket: true # default false
  producers:
    events:
      exchange_options:
        name:   'events'
        type:   'topic'
    cron:
      exchange_options: {name: 'cron', type: direct}
      queue_options:    {name: 'cron'}
  consumers:
    cron:
      connection:       default
      exchange_options: {name: 'cron', type: direct}
      queue_options:    {name: 'cron'}
      callback:         cronrunner
      idle_timeout:     10
      idle_timeout_exit_code: 0
      qos_options:      {prefetch_size: 0, prefetch_count: '%workers%', global: false}
    events:
      connection:       default
      exchange_options: {name: 'events', type: topic}
      queue_options:
        exclusive: true
        routing_keys:
          - '#'
      callback:         events
      idle_timeout:     1
      idle_timeout_exit_code: 0
      qos_options:      {prefetch_size: 0, prefetch_count: 1, global: true}
    keepalive:
      connection:       default
      exchange_options: {name: 'events', type: topic}
      queue_options:
        exclusive: true
        routing_keys:   ['HA.#','Control.#']
      callback:         failover_tracker
      idle_timeout:     1
      idle_timeout_exit_code: 0
      qos_options:      {prefetch_size: 0, prefetch_count: 1, global: true}
    control:
      connection:       default
      exchange_options: {name: 'events', type: topic}
      queue_options:
        exclusive: true
        routing_keys:   ['Control.#']
      callback:         events
      idle_timeout:     1
      idle_timeout_exit_code: 0
      qos_options:      {prefetch_size: 0, prefetch_count: 1, global: true}
    rpc_servers:
      connection:       default
      exchange_options: {name: 'master.rpc', type: direct}
      queue_options:    {name: 'master.rpc'}
      qos_options:      {prefetch_size: 0, prefetch_count: 1, global: true}
      callback:         rpc_server
