# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
  command.cron:
    class: CCronBundle\Command\CronCommand
    lazy: true
    tags:
        - { name: console.command }
    autowire: true
  command.master:
    class: CCronBundle\Command\MasterCommand
    lazy: true
    tags:
        - { name: console.command }
    autowire: true
  cronrunner:
    class: CCronBundle\Cron\Runner
    lazy: true
    calls:
      - [setWorkerPool, ['@workerpool']]
      - [setJobTracker, ['@job_tracker']]
      - [setLogger, ['@logger']]
      - [setMultiConsumer, ['@multi.consumer']]
      - [setRunning, ['@running']]
      - [setControlConsumer, ['@old_sound_rabbit_mq.control_consumer']]
      - [setCronConsumer, ['@cron_consumer']]
      - [setEntityManager, ['@doctrine.orm.default_entity_manager']]
      - [setWorkers, ['%workers%']]
  workerpool:
    class: QXS\WorkerPool\WorkerPool
    lazy: true
    calls:
      - [setChildProcessTitleFormat, ['%%basename%%: Worker %%i%% [%%state%%]']]
      - [setParentProcessTitleFormat, ['%%basename%%: Cron Runner']]
      - [setWorkerPoolSize, ['%workers%']]
  worker:
    class: CCronBundle\Cron\Worker
    lazy: true
  events:
    class: CCronBundle\Cron\EventProcessor
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  job_tracker:
    class: CCronBundle\Cron\JobTracker
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  master:
    class: CCronBundle\Cron\Master
    lazy: true
    arguments:
      - '@clock'
    calls:
      - [setEntityManager, ['@doctrine.orm.default_entity_manager']]
      - [setFailoverTracker, ['@failover_tracker']]
      - [setRPCServer, ['@old_sound_rabbit_mq.rpc_servers_consumer']]
      - [setKeepaliveConsumer, ['@old_sound_rabbit_mq.keepalive_consumer']]
      - [setMasterConsumer, ['@multi.consumer']]
      - [setLogger, ['@logger']]
      - [setHostnameDeterminer, ['@hostname_determiner']]
      - [setRunning, ['@running']]
      - [setJobQueuer, ['@jobQueuer']]
  jobQueuer:
    class: CCronBundle\Cron\JobQueuer
    lazy: true
    arguments:
      - '@clock'
    calls:
      - [setCronProducer, ['@old_sound_rabbit_mq.cron_producer']]
      - [setLogger, ['@logger']]
  clock:
    class: CCronBundle\SystemClock
    lazy: true
  failover_tracker:
    class: CCronBundle\Cron\FailoverTracker
    lazy: true
    arguments:
      - '@clock'
    calls:
      - [setContainer, ['@service_container']]
      - [setKeepaliveTime, ['%keepalive.time%']]
  hostname_determiner:
    class: CCronBundle\Cron\HostnameDeterminer
    lazy: true
  rpc_server:
    class: CCronBundle\Cron\RPCServer
    lazy: true
  multi.consumer:
    arguments: ['@old_sound_rabbit_mq.connection.default',null,null]
    class: CCronBundle\Cron\MultiConsumer
    lazy: true
    calls:
      - [setIdleTimeout, ['1']]
      - [setIdleTimeoutExitCode, ['0']]
      - [setHostnameDeterminer, ['@hostname_determiner']]
      - [setLogger, ['@logger']]
  running:
    class: CCronBundle\Cron\Running
    lazy: true
    arguments: [ '@logger' ]
  event_sender:
    class: CCronBundle\Events\EventSender
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  cron_consumer:
    class: CCronBundle\Cron\CronConsumer
    lazy: true
    arguments: [ '@old_sound_rabbit_mq.connection.default',null,null]
    calls:
      - [setCallback, [['@cronrunner','execute']]]
      - [setExchangeOptions, [{name: 'cron', type: direct}]]
      - [setQueueOptions, [{name: 'cron'}]]
      - [setQosOptions, ['0', '%workers%', 'false']]

  app.form.type.cron:
    class: CCronBundle\Form\CronType
    lazy: true
    tags:
      - { name: form.type }
  session.handler.pdo:
    class:     Symfony\Bridge\Doctrine\HttpFoundation\DbalSessionHandler
    public:    false
    lazy: true
    arguments:
      - '@doctrine.dbal.default_connection'
