# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  workers: 3
  keepalive.time: 5

services:
  cronrunner:
    class: CCronBundle\Cron\Runner
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  workerpool:
    class: QXS\WorkerPool\WorkerPool
    lazy: true
    calls:
      - [setWorkerPoolSize, ['%workers%']]
  worker:
    class: CCronBundle\Cron\Worker
    lazy: true
  events:
    class: CCronBundle\Cron\EventProcessor
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  job_tracker:
    class: CCronBundle\Cron\JobTracker
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  master:
    class: CCronBundle\Cron\Master
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
  failover_tracker:
    class: CCronBundle\Cron\FailoverTracker
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
      - [setKeepaliveTime, ['%keepalive.time%']]
  hostname_determiner:
    class: CCronBundle\Cron\HostnameDeterminer
    lazy: true
  rpc_server:
    class: CCronBundle\Cron\RPCServer
    lazy: true
  master_consumer:
    arguments: ['@old_sound_rabbit_mq.connection.default',null,null]
    class: CCronBundle\Cron\MultiConsumer
    lazy: true
    calls:
      - [setContainer, ['@service_container']]
      - [setIdleTimeout, ['1']]
      - [setIdleTimeoutExitCode, ['0']]
  running:
    class: CCronBundle\Cron\Running
  event_sender:
    class: CCronBundle\Events\EventSender
    calls:
      - [setContainer, ['@service_container']]
    lazy: true
